name: 'edge_telegram_bot'
description: 'A sample command-line application.'
version: '0.0.0'
homepage: 'https://github.com/{main_username_owner}/general'
repository: 'https://github.com/{main_username_owner}/edge_telegram_bot'
issue_tracker: 'https://github.com/{main_username_owner}/general/issues'
documentation: 'https://github.com/{main_username_owner}/edge_telegram_bot/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
  
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '^3.2.3'
  
dev_dependencies:
  build_runner: ^2.3.3
  isar_generator: ^3.1.0+1
  lints: '^2.1.0'
  test: '^1.24.0' 

dependencies:
  packagex: ^0.0.44
  encrypt: ^5.0.1
  general_lib: ^0.0.27
  image: ^4.1.3
  intl: ^0.18.1 

  path: ^1.8.3  
  supabase: ^2.0.5 
  
  telegram_client: ^0.8.0
  edge_dart: ^0.0.3
  edge_dart_http_client: ^0.0.1
  edge_supabase: ^0.0.1
  universal_io: ^2.2.2
  isar: ^3.1.0+1
  http: ^1.1.2
  meta: ^1.11.0
  yet_another_json_isolate: ^2.0.0
  collection: ^1.18.0
  general_dart: ^0.0.17
  mason_logger: ^0.2.12
